### ISSUE TITLE
Optimize image loading

### ISSUE THREAD

**Issue by nazmulidris** [MaretIdris/portfolio2020#24]
FB recruiter saw problems on his machine (unknown internet connection speed) loading large images on the UAMP page. 

1) Figure out ways to preload the images
2) Provide thumbnails / high res image bundles

**Comment by nazmulidris** [comment]
@MaretIdris 
Another approach could be to use placeholder images which are correctly sized inline svg images eg: `url('data:image/svg+xml;utf8,<svg width="24px" height="24px"></svg>')`. This loads instantly and then can be replaced in JS asynchronously w/ the really high res (and slow) image, after all the HTML has loaded or component has mounted.

**Comment by MaretIdris** [comment]
Use [ShortPixel ](https://shortpixel.com/) to reduce the image sizes.

**Comment by MaretIdris** [comment]
Fixes 4c2a17353d60306c46649686f8ab5ffed7d23c8d
