### ISSUE TITLE
Make the navbar auto show/hide only when viewport is smaller than 600px and blur the larger viewport navbar

### ISSUE THREAD

**Issue by MaretIdris** [MaretIdris/portfolio2020#26]
- Also change the navbar background to blurry when viewport is larger than 600px.

**Comment by nazmulidris** [comment]
Here's a good website https://linear.app/ to serve an example of blurring the navbar. It is fixed permanently (on desktop) and has a blur effect when content slides underneath it. 

This is desirable behavior on desktop (tall / large screens) but on mobile there is value to simply removing the navbar (which is the current behavior).

**Comment by MaretIdris** [comment]
`backdrop-filter` is an experimental feature. By adding it to the #app-bar CSS selector, it broke the Designs and Code dropdowns on JS mouseenter and mouseleave events. 

It would take too much time to figure this out, but the benefit is not that impactful. So I decided to drop `backdrop-filter` feature for now.
