### ISSUE TITLE
Cross browser compatibility issues (Firefox and Safari)

### ISSUE THREAD

**Issue by nazmulidris** [MaretIdris/portfolio2020#29]
# Safari and Firefox:
Repro steps
1) Open firefox
2) Load http://maretidris.com
3) Click on a TruckX
4) Scroll down to the bottom of the page and click on Design Projects -> Abbey Road Studios
5) Notice that it navigates to the correct destination page, however, the scroll to top event never fires.

# Safari:
- When navigating to a destination page (after the site has loaded), the nav bar does not appear.
- When scroll down at least 64 px and then up again, then nav bar appears.

**Comment by MaretIdris** [comment]
Safari: 
- When navigating to a destination page (after the site has loaded), the nav bar does not appear.
- When scroll down at least 64 px and then up again, then nav bar appears.

**Comment by nazmulidris** [comment]
9a55dfd67157a8075bba4c38a3d010d43392c1a3 addresses the CSS styling issues in Firefox and Safari. However, Safari needs more work to make it better.

**Comment by nazmulidris** [comment]
Approaches to fixing the scrolling issue.

1) Remove the shared method that changes page destination by changing state
2) Go back to using `<a href=?page=TruckX/>` as an example

There is a problem with the `window.scrollTo()` implementation on different browsers. This does not reliably fire the same types of browser events across all the browsers. Eg: in Safari, it does scroll, but does not fire `window.scroll` function! And it doesn't even reliably scroll up the entire page when it is "working" (sometimes).

**Comment by nazmulidris** [comment]
@MaretIdris 
We should use react router in the future as a separate issue

**Comment by MaretIdris** [comment]
85cd5ee does not fix the problem w/ the nav bar not showing correctly in safari when the window.scrollTo top occurs. The solution entails creating a new function that immediately shows the nav bar even when it is hidden.

**Comment by MaretIdris** [comment]
0b5aa31c6b6baeae3d1e7774411221434373e8d4 fixes responsive image on about page in Safari.
